# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb0594d14bac6e849ede744537a4f39bfc42002b001ed25b4fbe69df0e801dabdb7c326ff1e5aa75fb172eb02b86a12bdfbb6ef71078107fc3dc8b75a2165835

test:
  secret_key_base: 588b9913fe461f4729176549d6f5fc7ea2357d093cf9671d4cfac28965ff92df4a605a8c3a42e43635ad7e30fc65f33632bb3d61db09fca0a6ec4f101e589cd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
